version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - sscore.backend
      - sscore.frontend

  sscore.backend:
    container_name: schoolsynccore-backend
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mgms_db
      - SPRING_DATASOURCE_USERNAME=mgms_user
      - SPRING_DATASOURCE_PASSWORD=mgms_password
    depends_on:
      - schoolsynccore-database
    volumes:
      - ./target/school-sync-core.war:/usr/local/tomcat/webapps/school-sync-core.war:ro

  sscore.frontend:
    container_name: schoolsynccore-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "3000"
    depends_on:
      - sscore.backend

  schoolsynccore-database:
    image: postgres:13
    environment:
      - POSTGRES_DB=mgms_db
      - POSTGRES_USER=mgms_user
      - POSTGRES_PASSWORD=mgms_password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
