version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "3000:3000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mgms_db
      - SPRING_DATASOURCE_USERNAME=mgms_user
      - SPRING_DATASOURCE_PASSWORD=mgms_password
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=mgms_db
      - POSTGRES_USER=mgms_user
      - POSTGRES_PASSWORD=mgms_password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: